spring:
  application:
    name: joom

  data:
    redis:
      # 📌 환경 변수가 들어오면 그 값을 쓰고, 없으면 기본값으로 localhost를 사용합니다.
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: 0
      
management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health, info" #prometheus 엔드포인트개방
    endpoint:
      health:
        show-details: always
      metrics:
        tags:
          application: joom-backend #그라파나에서 식별할 앱이름

