name: Deploy SFU Server

on:
  push:
    branches: ["master","main"]
    paths:
      - 'sfu-server/**'
      - 'joom-client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🛠️ 기준점을 최상위 루트로 잡고 도면 파일의 상대 경로를 지정하는 정석 명령어입니다.
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/joom-sfu:latest -f sfu-server/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/joom-sfu:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.EC2_SFU_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop joom-sfu || true
            docker rm joom-sfu || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/joom-sfu:latest
            docker run -d --name joom-sfu \
              --network host \
              --restart always \
              -e REDIS_HOST="${{ secrets.REDIS_HOST }}" \
              -e ANNOUNCED_IP="${{ secrets.EC2_SFU_HOST }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/joom-sfu:latest